### ISSUE TITLE
Link!

### ISSUE THREAD

**Issue by roelvangils** [Obra-Studio/obra-icons-svelte-public#1]
Cool icon set! 

Johan, your link does not yet point to this repository! 😉 

![20231001_201023_Arc@2x](https://github.com/Obra-Studio/obra-icons-svelte/assets/103744/e45fbe30-4816-426b-b0a0-1716f7b20bf6)

And GitHub is spelled with a capital H! 😉

**Comment by Wolfr** [comment]
@roelvangils Thank you :) I fixed both!
