### ISSUE TITLE
icons are not responsive to font-size

### ISSUE THREAD

**Issue by anxpara** [Obra-Studio/obra-icons-svelte-public#3]
I installed the svelte package and tried the icons out. they look great, but they don't respond to font-size. The width and height of the icons should be set in em, not px. (by default, 1rem is 16px, so 24px is equivalent to 1.5em)

**Comment by Wolfr** [comment]
@anxpara You can resize them using the size prop, does this help you?

https://svelte.dev/repl/eff0004eec214e87bd1a3d8e04579dea?version=4.2.1

Example:
`<IconAdd size="32" />`

SVGs do not work with pixel or em units afaik, only coordinates in the viewbox. I don't know of any way to scale an SVG with the font size.

If you can provide a demo of what you are after with a regular SVG, it would be helpful.

Edit: here's a demo of how you would scale the icons using CSS https://svelte.dev/repl/1dcf7a689807415cbd475af81f34b905?version=4.2.1

**Comment by anxpara** [comment]
What's stopping you from setting "height: 1em; width: 1em;" as the default within the obra icons source, so that users don't have to use :global() for this?

And side note: 1em is probably better than the 1.5em i mentioned earlier, so that icons fit with any text they're next to. For example, I have a copy icon next to my email, and it looks good when their line heights match.

**Comment by Wolfr** [comment]
I could do that but I think people might want to set their own CSS? Inlining this in every component makes it hard to override globally. Sent from my iPhoneOn 18 Oct 2023, at 15:35, anxpara ***@***.***> wrote:﻿
What's stopping you from setting "height: 1em; width: 1em;" as the default within the obra icons source, so that users don't have to use :global() for this?
And side note: 1em is probably better than the 1.5em i mentioned earlier, so that icons fit with any text they're next to. For example, I have a copy icon next to my email, and it looks good when their line heights match.

**Comment by anxpara** [comment]
i think most people would expect the icons to be responsive to the context they are added to, rather than having a fixed, global size.

take the google icons api, for example. I can put those icons in any header (```<h1>, <h2>, <p>```, etc.), and they will scale as expected to match the text they are next to. I would check out google icons and try to follow their behavior

"people might want to set their own CSS"

they would be able to do that if the icons were responsive to font-size, simply by changing the font size of the parent

"Inlining this in every component..."

i haven't looked at your code, but this shouldn't require a separate inlined style for every icon in your repo. there should be a way to set it once. inlined styles generally aren't the best approach.

"...makes it hard to override globally"

i honestly don't think :global() is an ideal way to interface with a svelte package. so far, your examples for controlling obra icons usually look like this:

```
p :global(svg) {
  // override styles...
}
```

the first problem here is that there's nothing specific to obra. maybe the user has their own svgs within paragraphs somewhere else, and this rule would mess with those svgs.

the second problem is that setting styles globally shouldn't be the first option one reaches for. it's fine if one definitely wants global control, or if there are no other options. but i don't a svelte package should require global styling, nor make that the defacto way to control style.

---

if you still wanted to support this use case, i imagine you'd want to create a common class for your icons, like ".obra-icon", which would specify the default width/height of 1em. all the icons in your repo would use that class, and then users could control the size both locally with parent font-size, and globally, with ":global(.obra-icon) { width: $userWidth; }"

**Comment by brechtDR** [comment]
In my experience, I believe that if you can scale them by setting a width in (r)em using CSS, it should be ok. 
Seems the normal way to me when it's not an icon font, but I might be biased because I do it that way in my SVG sprites. I just set the size to a default with all my icons having the same viewbox and scale with CSS.

Maybe I fail to see the issue.

**Comment by Wolfr** [comment]
@anxpara If every icon can be targeted with `class=“obra-icon”` would that be satisfactory to you?

This way, authors can decide for themselves which type of sizing they want to use (em, rem, px...).

**Comment by anxpara** [comment]
it should still respond to font size by default, like Google icons

**Comment by Wolfr** [comment]
@anxpara are you talking about Google Icons as an icon font?

**Comment by anxpara** [comment]
these: https://fonts.google.com/icons

**Comment by Wolfr** [comment]
@anxpara Google Icons as linked is an icon font, this is a different technology than embedding SVGs.

Now I understand our conversation better.

I've always liked icon fonts, and I will definitely consider implementing an icon font option for Obra Icons.

**Comment by anxpara** [comment]
Personally, i think svg icon sets and icon fonts should behave the same wrt responding to font size. But if you prefer to reserve that behavior for an icon font variant of obra, then as long as you define the default values in a common css class like .obra-icon then i would be able to achieve that behavior for my own use case

**Comment by Wolfr** [comment]
@anxpara Based on your feedback I implemented this the option to scale with a specific CSS class.

See this demo here: https://svelte.dev/repl/5446e2b985744e808fa4b7612aa330e0?version=4.2.2 .

I am considering an icon font but I highly optimized the pipeline so far for an SVG component flow. The process is highly automated. Adding an icon font feature would involve a lot of work, but I am not ruling it out.

**Comment by anxpara** [comment]
adding the obra-icon class covers this issue. i'd say adding an icon font to your workflow is lower priority

thanks Wolfr!

**Comment by Wolfr** [comment]
Super!
